//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniBank.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with ID {0} created successfully.
        /// </summary>
        internal static string AccountCreatedMsg {
            get {
                return ResourceManager.GetString("AccountCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with ID {0} deleted successfully.
        /// </summary>
        internal static string AccountDeletedMsg {
            get {
                return ResourceManager.GetString("AccountDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID: {0} | Type: {1} | Balance: {2}.
        /// </summary>
        internal static string AccountFormat {
            get {
                return ResourceManager.GetString("AccountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account ID:.
        /// </summary>
        internal static string AccountIdInputMsg {
            get {
                return ResourceManager.GetString("AccountIdInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId.
        /// </summary>
        internal static string AccountIdVarName {
            get {
                return ResourceManager.GetString("AccountIdVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with ID {0} not found..
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        internal static string AccountsTableName {
            get {
                return ResourceManager.GetString("AccountsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Accounts ===.
        /// </summary>
        internal static string AccountsViewHeader {
            get {
                return ResourceManager.GetString("AccountsViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account type:.
        /// </summary>
        internal static string AccountTypeInputMsg {
            get {
                return ResourceManager.GetString("AccountTypeInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action:.
        /// </summary>
        internal static string ActionInputMsg {
            get {
                return ResourceManager.GetString("ActionInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount:.
        /// </summary>
        internal static string AmountInputMsg {
            get {
                return ResourceManager.GetString("AmountInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string BalanceVarName {
            get {
                return ResourceManager.GetString("BalanceVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice is out of range, please try again..
        /// </summary>
        internal static string ChoiceOutOfRange {
            get {
                return ResourceManager.GetString("ChoiceOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB.
        /// </summary>
        internal static string DBVarName {
            get {
                return ResourceManager.GetString("DBVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit {0} to acoount {1} successfully.
        /// </summary>
        internal static string DepositMsg {
            get {
                return ResourceManager.GetString("DepositMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        ///Stack trace: {1}.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Bank is closed.
        ///Come back soon....
        /// </summary>
        internal static string ExitMsg {
            get {
                return ResourceManager.GetString("ExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOST.
        /// </summary>
        internal static string HostVarName {
            get {
                return ResourceManager.GetString("HostVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string IdVarName {
            get {
                return ResourceManager.GetString("IdVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insufficient balance..
        /// </summary>
        internal static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string MenuItemFormat {
            get {
                return ResourceManager.GetString("MenuItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name: .
        /// </summary>
        internal static string NameInputMsg {
            get {
                return ResourceManager.GetString("NameInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameVarName {
            get {
                return ResourceManager.GetString("NameVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string PasswordVarName {
            get {
                return ResourceManager.GetString("PasswordVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string SimpleVarName {
            get {
                return ResourceManager.GetString("SimpleVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeVarName {
            get {
                return ResourceManager.GetString("TypeVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported account type: {0}.
        /// </summary>
        internal static string UnsoppertedAccount {
            get {
                return ResourceManager.GetString("UnsoppertedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to useraccounts.
        /// </summary>
        internal static string UserAccountsTableName {
            get {
                return ResourceManager.GetString("UserAccountsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID {0} created successfully.
        /// </summary>
        internal static string UserCreatedMsg {
            get {
                return ResourceManager.GetString("UserCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID {0} deleted successfully.
        /// </summary>
        internal static string UserDeletedMsg {
            get {
                return ResourceManager.GetString("UserDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string UserFormat {
            get {
                return ResourceManager.GetString("UserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user ID: .
        /// </summary>
        internal static string UserIdInputMsg {
            get {
                return ResourceManager.GetString("UserIdInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        internal static string UserIdVarName {
            get {
                return ResourceManager.GetString("UserIdVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERNAME.
        /// </summary>
        internal static string UsernameVarName {
            get {
                return ResourceManager.GetString("UsernameVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID {0} not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string UsersTableName {
            get {
                return ResourceManager.GetString("UsersTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Users ===.
        /// </summary>
        internal static string UsersViewHeader {
            get {
                return ResourceManager.GetString("UsersViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip.
        /// </summary>
        internal static string VipVarName {
            get {
                return ResourceManager.GetString("VipVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw {0} from acoount {1} successfully.
        /// </summary>
        internal static string WithdrawMsg {
            get {
                return ResourceManager.GetString("WithdrawMsg", resourceCulture);
            }
        }
    }
}
