//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniBank.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId.
        /// </summary>
        internal static string AccountIdVarName {
            get {
                return ResourceManager.GetString("AccountIdVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with ID {0} not found..
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string AccountsTableName {
            get {
                return ResourceManager.GetString("AccountsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string BalanceVarName {
            get {
                return ResourceManager.GetString("BalanceVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB.
        /// </summary>
        internal static string DBVarName {
            get {
                return ResourceManager.GetString("DBVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string IdVarName {
            get {
                return ResourceManager.GetString("IdVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insufficient balance..
        /// </summary>
        internal static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameVarName {
            get {
                return ResourceManager.GetString("NameVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWD.
        /// </summary>
        internal static string PWDVarName {
            get {
                return ResourceManager.GetString("PWDVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOST.
        /// </summary>
        internal static string ServerVarName {
            get {
                return ResourceManager.GetString("ServerVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string SimpleVarName {
            get {
                return ResourceManager.GetString("SimpleVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeVarName {
            get {
                return ResourceManager.GetString("TypeVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        internal static string UIDVarName {
            get {
                return ResourceManager.GetString("UIDVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported account type: {0}.
        /// </summary>
        internal static string UnsoppertedAccount {
            get {
                return ResourceManager.GetString("UnsoppertedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAccounts.
        /// </summary>
        internal static string UserAccountsTableName {
            get {
                return ResourceManager.GetString("UserAccountsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        internal static string UserIdVarName {
            get {
                return ResourceManager.GetString("UserIdVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID {0} not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersTableName {
            get {
                return ResourceManager.GetString("UsersTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip.
        /// </summary>
        internal static string VipVarName {
            get {
                return ResourceManager.GetString("VipVarName", resourceCulture);
            }
        }
    }
}
